V3 updates
ArrowDFMs/arrow-markets-sdk pull request #7
Opened 2022-08-18 19:05 UTC by tenax002

2022-08-18 23:36 UTC, tenax002 commented on examples/place-option-order.ts
> +    const readableExpiration = "08192022"
Just noticed this is hard coded. Updating to dynamically select the nearest Friday expiration so this test file won't fail in the future.

2022-08-19 00:20 UTC, Pdbz199 requested changes
Small comments

2022-08-19 00:20 UTC, Pdbz199 commented on examples/place-option-order.ts
> +    //TO-DO- Update API to ensure it is generating the correct option chain address
I guess we should remove this

2022-08-19 00:20 UTC, Pdbz199 commented on src/arrow-sdk.ts
> +import * as moment from "moment"
lets use single quotes to be consistent

2022-08-19 00:20 UTC, Pdbz199 commented on examples/place-option-order.ts
> +import * as moment from "moment"
can we use single quotes here to be the same as other imports?

2022-08-19 00:26 UTC, Pdbz199 approved these changes

2022-08-19 00:26 UTC, merged