Support fuji v3 updates
ArrowDFMs/arrow-markets-sdk pull request #9
Opened 2022-09-13 14:16 UTC by tenax002

2022-09-15 17:00 UTC, Pdbz199 requested changes
Left comments and I guess we also need to think about removing the competition API for now if we want to use this version of the SDK

2022-09-15 17:00 UTC, Pdbz199 commented on src/arrow-sdk.ts
> +  IArrowRegistry,
I don't think I can, in good conscience, accept a change that adds a comma to the end of a list 😅

2022-09-15 17:00 UTC, Pdbz199 commented on src/arrow-sdk.ts
> +  rho: number;
Do you know why we used to have commas and now have semicolons?

2022-09-15 17:00 UTC, Pdbz199 commented on src/arrow-sdk.ts
> +  V2 = "v2",
As we discussed, we should remove V2 from the new SDK version

2022-09-15 17:00 UTC, Pdbz199 commented on src/arrow-sdk.ts
> -    "api": {
So much space removed, kinda sad because 4 space tabs are very nice n readable 😭

2022-09-15 17:00 UTC, Pdbz199 commented on src/arrow-sdk.ts
> +  version: VERSION = VERSION.V2
Let's default to V3

2022-09-15 17:00 UTC, Pdbz199 commented on src/arrow-sdk.ts
> +  //TO DO Get HISTORICAL PRICE IF PRICE HISTORY IS NULL
For TODO comments you must make sure it looks like this: `// TODO: Get historical price if price history is NULL`

2022-09-15 17:00 UTC, Pdbz199 commented on src/arrow-sdk.ts
> +      expiration: deliverOptionParams.expiration, // readableExpiration
I guess we can change the comment here to say `// readable expiration` since its not necessarily referring to a variable, just the expected type of expiration.

2022-09-15 17:00 UTC, Pdbz199 commented on src/arrow-sdk.ts
> +    case "LINK":
Let's remove LINK here too

2022-09-15 17:00 UTC, Pdbz199 commented on src/arrow-sdk.ts
> +  const dayOfTheWeek: number = (Math.floor(unixExpiration / 86400) + 4) % 7;
Can you make `86400` into its constituent parts like `60 * 60 * 24` since it's more clear what it actually means?

2022-09-15 17:00 UTC, Pdbz199 commented on src/arrow-sdk.ts
> + * @returns True if provided unixExpiration is a Friday
Can you make the change so that we have `...is a Friday, else returns False`?

2022-09-15 17:00 UTC, Pdbz199 commented on src/arrow-sdk.ts
> +      [0, 2].includes(optionOrderParams.order_type),
Can you explain this line to me? It might also help to have an ENUM of OrderType in the SDK. 0 is LONG_OPEN, 1 is LONG_CLOSE, 2 is SHORT_OPEN, and 3 is SHORT_CLOSE. I think we are looking for `[0, 1].includes...` instead...

2022-09-16 15:08 UTC, tenax002 commented on src/arrow-sdk.ts
> +  rho: number;
I have eslint and prettify installed and every-time I save it updates it. Osama had me install it so the UI code can be uniform in terms of formatting

2022-09-16 15:32 UTC, tenax002 commented on src/arrow-sdk.ts
> +      [0, 2].includes(optionOrderParams.order_type),
Yup that is right

2022-09-16 15:37 UTC, tenax002 commented on src/arrow-sdk.ts
> +  IArrowRegistry,
Yeah eslint keeps adding it. I can disable it and commit lol

2022-09-16 16:50 UTC, Pdbz199 approved these changes

2022-09-16 16:52 UTC, merged